cc_library(
    name = "esp_common",
    srcs = glob(["src/**/*.c"]),
    hdrs = glob(["**/*.h"]),
    includes = [
        "include"
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//roo_testing/frameworks/esp-idf-v4.4.1:sdkconfig",
    ],
)
