cc_library(
    name = "esp_common",
    srcs = glob(["**/*.cpp"]) + glob(["src/**/*.c"]),
    hdrs = glob(["**/*.h"]),
    includes = [
        "include"
    ],
    visibility = ["//visibility:public"],
)
