
cc_library(
    name = "spi",
    srcs = ["st77xx.cpp"],
    hdrs = ["st77xx.h"],
    deps = [
        "//roo_testing/buses/spi",
        "//roo_testing/transducers/ui/viewport",
        "@com_github_google_glog//:glog",
    ],
    visibility = ["//visibility:public"],
)

