cc_library(
    name = "soc",
    # srcs = glob(["*.cpp"]) + glob(["*.c"]),
    hdrs = glob(["**/*.h"]),
    includes = [
        "include"
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//roo_testing/frameworks/esp-idf-v4.4.1:sdkconfig",
        # "//roo_testing/frameworks/esp-idf-v4.4.1/components/esp_common",
        # "//roo_testing/frameworks/esp-idf-v4.4.1/components/soc/esp32",
        # "//roo_testing/frameworks/esp-idf-v4.4.1/components/freertos",
        # "//roo_testing/frameworks/esp-idf-v4.4.1/components/esp_hw_support",
    ]
)
