cc_library(
    name = "roo_display_generic",
    srcs = [
        "reference_device.cpp",
        "reference_device.h",
    ],
    deps = [
        "//lib/roo_display",
        "//lib/roo_time",
        "//roo_testing/transducers/ui/viewport",
    ],
    visibility = ["//visibility:public"],
)
