/*
 * Host configuration for roo_testing.
 *
 * ESP-IDF normally generates this header with kconfig.  roo_testing does not
 * use IDF's target build, so keep the small set of host-facing options here.
 * The values follow the ESP-IDF 5.5 Linux defaults, with a 1 kHz tick and the
 * tick hook enabled for delivery of roo_testing host events.
 */
#pragma once

/* Build and target identity. */
#define CONFIG_IDF_CMAKE 1
#ifndef CONFIG_IDF_TARGET
#define CONFIG_IDF_TARGET "linux"
#endif
#define CONFIG_IDF_TARGET_LINUX 1
#define CONFIG_SOC_CPU_CORES_NUM 1
#define CONFIG_ESP_SYSTEM_SINGLE_CORE_MODE 1

/* Compiler settings consumed by common ESP-IDF headers. */
#define CONFIG_COMPILER_OPTIMIZATION_SIZE 1
#define CONFIG_COMPILER_CXX_EXCEPTIONS 1
#define CONFIG_COMPILER_CXX_EXCEPTIONS_EMG_POOL_SIZE 0
#define CONFIG_COMPILER_CXX_RTTI 1
#define CONFIG_COMPILER_STACK_CHECK_MODE_NONE 1
#define CONFIG_COMPILER_WARN_WRITE_STRINGS 1
#define CONFIG_COMPILER_OPTIMIZATION_ASSERTIONS_ENABLE 1
#define CONFIG_COMPILER_OPTIMIZATION_ASSERTION_LEVEL 2

/* FreeRTOS kernel selection and scheduler. */
#define CONFIG_FREERTOS_UNICORE 1
#define CONFIG_FREERTOS_NUMBER_OF_CORES 1
#define CONFIG_FREERTOS_NO_AFFINITY 0x7fffffff
#define CONFIG_FREERTOS_HZ 1000
#define CONFIG_FREERTOS_TICK_RATE_HZ CONFIG_FREERTOS_HZ
#define CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ 160
#define CONFIG_FREERTOS_MAX_TASK_NAME_LEN 16
#define CONFIG_FREERTOS_IDLE_TASK_STACKSIZE 4096
#define CONFIG_FREERTOS_ISR_STACKSIZE 1536
#define CONFIG_FREERTOS_THREAD_LOCAL_STORAGE_POINTERS 1
#define CONFIG_FREERTOS_TLSP_DELETION_CALLBACKS 1
#define CONFIG_FREERTOS_TASK_NOTIFICATION_ARRAY_ENTRIES 1
#define CONFIG_FREERTOS_USE_APPLICATION_TASK_TAG 1
#define CONFIG_FREERTOS_QUEUE_REGISTRY_SIZE 0
#define CONFIG_FREERTOS_CHECK_MUTEX_GIVEN_BY_OWNER 1

/* Hooks and stack checking.  The tick hook feeds HostEventGateway. */
#define CONFIG_FREERTOS_USE_TICK_HOOK 1
#define CONFIG_FREERTOS_IDLE_TIME_BEFORE_SLEEP 3
#define CONFIG_FREERTOS_CHECK_STACKOVERFLOW_NONE 1

/* Software timers. */
#define CONFIG_FREERTOS_USE_TIMERS 1
#define CONFIG_FREERTOS_TIMER_SERVICE_TASK_NAME "Tmr Svc"
#define CONFIG_FREERTOS_TIMER_TASK_AFFINITY_CPU0 1
#define CONFIG_FREERTOS_TIMER_SERVICE_TASK_CORE_AFFINITY 0x0
#define CONFIG_FREERTOS_TIMER_TASK_PRIORITY 1
#define CONFIG_FREERTOS_TIMER_TASK_STACK_DEPTH 2053
#define CONFIG_FREERTOS_TIMER_QUEUE_LENGTH 10

/* Host-safe inspection support used by ESP-IDF's task additions. */
#define CONFIG_FREERTOS_ENABLE_TASK_SNAPSHOT 1

/* Features deliberately disabled in the host emulator. */
#define CONFIG_FREERTOS_RUN_TIME_COUNTER_TYPE_U32 1

/* Generic ESP-IDF/Arduino task defaults used by public headers. */
#define CONFIG_ESP_MAIN_TASK_STACK_SIZE 8192
#define CONFIG_ESP_MAIN_TASK_AFFINITY_CPU0 1
#define CONFIG_ESP_MAIN_TASK_AFFINITY 0x0
#define CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE 2304
#define CONFIG_ESP_SYSTEM_EVENT_TASK_AFFINITY_CPU0 1
#define CONFIG_ESP_SYSTEM_EVENT_TASK_AFFINITY 0x0
#define CONFIG_ESP_TIMER_TASK_STACK_SIZE 3584
#define CONFIG_ESP_TIMER_TASK_AFFINITY_CPU0 1
#define CONFIG_ESP_TIMER_TASK_AFFINITY 0x0
#define CONFIG_ESP_TIMER_TASK_PRIORITY 22
#define CONFIG_PTHREAD_TASK_PRIO_DEFAULT 5
#define CONFIG_PTHREAD_TASK_STACK_SIZE_DEFAULT 3072
#define CONFIG_PTHREAD_STACK_MIN 768
#define CONFIG_PTHREAD_TASK_CORE_DEFAULT -1
#define CONFIG_PTHREAD_TASK_NAME_DEFAULT "pthread"

/* Logging defaults expected by ESP-IDF and Arduino public headers. */
#define CONFIG_LOG_DEFAULT_LEVEL_INFO 1
#define CONFIG_LOG_DEFAULT_LEVEL 3
#define CONFIG_LOG_MAXIMUM_LEVEL_DEBUG 1
#define CONFIG_LOG_MAXIMUM_LEVEL 4
#define CONFIG_LOG_COLORS 1
#define CONFIG_LOG_TIMESTAMP_SOURCE_RTOS 1
#define CONFIG_LOG_TAG_LEVEL_IMPL_NONE 1
#define CONFIG_LOG_TAG_LEVEL_IMPL 0

/* Arduino-as-a-component defaults; its custom main remains responsible for
 * starting the scheduler in roo_testing. */
#define CONFIG_AUTOSTART_ARDUINO 1
#define CONFIG_ARDUINO_LOOP_STACK_SIZE 8192
#define CONFIG_ARDUINO_RUNNING_CORE 0
#define CONFIG_ARDUINO_EVENT_RUNNING_CORE 0
#define CONFIG_ARDUINO_SERIAL_EVENT_TASK_RUNNING_CORE -1
#define CONFIG_ARDUINO_SERIAL_EVENT_TASK_STACK_SIZE 2048
#define CONFIG_ARDUINO_SERIAL_EVENT_TASK_PRIORITY 24
#define CONFIG_ARDUHAL_LOG_DEFAULT_LEVEL 1
#define CONFIG_ARDUHAL_ESP_LOG 1

/* Compatibility names retained by ESP-IDF public APIs. */
#define CONFIG_MAIN_TASK_STACK_SIZE CONFIG_ESP_MAIN_TASK_STACK_SIZE
#define CONFIG_TIMER_TASK_PRIORITY CONFIG_FREERTOS_TIMER_TASK_PRIORITY
#define CONFIG_TIMER_QUEUE_LENGTH CONFIG_FREERTOS_TIMER_QUEUE_LENGTH
#define CONFIG_TIMER_TASK_STACK_DEPTH CONFIG_FREERTOS_TIMER_TASK_STACK_DEPTH
