/*
 * Host configuration for roo_testing.
 *
 * ESP-IDF normally generates this header with kconfig.  roo_testing does not
 * use IDF's target build, so keep the small set of host-facing options here.
 * The runtime settings follow the ESP-IDF Linux port, with a 1 kHz tick and
 * the tick hook enabled for delivery of roo_testing host events. Target
 * identity comes from //roo_testing/soc:target so public code sees the SoC
 * being emulated, rather than the machine that executes the test.
 */
#pragma once

/* Build and execution configuration. */
#define CONFIG_IDF_CMAKE 1
#include "roo_testing/soc_profile.h"

/* Classic ESP32 has two physical cores. The host scheduler remains
 * intentionally single-core through CONFIG_FREERTOS_NUMBER_OF_CORES below. */
#define CONFIG_SOC_CPU_CORES_NUM 2
#define CONFIG_ESP_SYSTEM_SINGLE_CORE_MODE 1

/* Compiler settings consumed by common ESP-IDF headers. */
#define CONFIG_COMPILER_OPTIMIZATION_SIZE 1
#define CONFIG_COMPILER_CXX_EXCEPTIONS 1
#define CONFIG_COMPILER_CXX_EXCEPTIONS_EMG_POOL_SIZE 0
#define CONFIG_COMPILER_CXX_RTTI 1
#define CONFIG_COMPILER_STACK_CHECK_MODE_NONE 1
#define CONFIG_COMPILER_WARN_WRITE_STRINGS 1
#define CONFIG_COMPILER_OPTIMIZATION_ASSERTIONS_ENABLE 1
#define CONFIG_COMPILER_OPTIMIZATION_ASSERTION_LEVEL 2

/* FreeRTOS kernel selection and scheduler. */
#define CONFIG_FREERTOS_UNICORE 1
#define CONFIG_FREERTOS_NUMBER_OF_CORES 1
#define CONFIG_FREERTOS_NO_AFFINITY 0x7fffffff
#define CONFIG_FREERTOS_HZ 1000
#define CONFIG_FREERTOS_TICK_RATE_HZ CONFIG_FREERTOS_HZ
#define CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ 240
#define CONFIG_FREERTOS_MAX_TASK_NAME_LEN 16
#define CONFIG_FREERTOS_IDLE_TASK_STACKSIZE 4096
#define CONFIG_FREERTOS_ISR_STACKSIZE 1536
#define CONFIG_FREERTOS_THREAD_LOCAL_STORAGE_POINTERS 1
#define CONFIG_FREERTOS_TLSP_DELETION_CALLBACKS 1
#define CONFIG_FREERTOS_TASK_NOTIFICATION_ARRAY_ENTRIES 1
#define CONFIG_FREERTOS_USE_APPLICATION_TASK_TAG 1
#define CONFIG_FREERTOS_QUEUE_REGISTRY_SIZE 0
#define CONFIG_FREERTOS_CHECK_MUTEX_GIVEN_BY_OWNER 1

/* Hooks and stack checking.  The tick hook feeds HostEventGateway. */
#define CONFIG_FREERTOS_USE_TICK_HOOK 1
#define CONFIG_FREERTOS_IDLE_TIME_BEFORE_SLEEP 3
#define CONFIG_FREERTOS_CHECK_STACKOVERFLOW_NONE 1

/* Software timers. */
#define CONFIG_FREERTOS_USE_TIMERS 1
#define CONFIG_FREERTOS_TIMER_SERVICE_TASK_NAME "Tmr Svc"
#define CONFIG_FREERTOS_TIMER_TASK_AFFINITY_CPU0 1
#define CONFIG_FREERTOS_TIMER_SERVICE_TASK_CORE_AFFINITY 0x0
#define CONFIG_FREERTOS_TIMER_TASK_PRIORITY 1
#define CONFIG_FREERTOS_TIMER_TASK_STACK_DEPTH 2053
#define CONFIG_FREERTOS_TIMER_QUEUE_LENGTH 10

/* Host-safe inspection support used by ESP-IDF's task additions. */
#define CONFIG_FREERTOS_ENABLE_TASK_SNAPSHOT 1

/* Features deliberately disabled in the host emulator. */
#define CONFIG_FREERTOS_RUN_TIME_COUNTER_TYPE_U32 1

/* Generic ESP-IDF/Arduino task defaults used by public headers. */
#define CONFIG_ESP_MAIN_TASK_STACK_SIZE 8192
#define CONFIG_ESP_MAIN_TASK_AFFINITY_CPU0 1
#define CONFIG_ESP_MAIN_TASK_AFFINITY 0x0
#define CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE 2304
#define CONFIG_ESP_SYSTEM_EVENT_TASK_AFFINITY_CPU0 1
#define CONFIG_ESP_SYSTEM_EVENT_TASK_AFFINITY 0x0
#define CONFIG_ESP_TIMER_TASK_STACK_SIZE 3584
#define CONFIG_ESP_TIMER_TASK_AFFINITY_CPU0 1
#define CONFIG_ESP_TIMER_TASK_AFFINITY 0x0
#define CONFIG_ESP_TIMER_TASK_PRIORITY 22
#define CONFIG_PTHREAD_TASK_PRIO_DEFAULT 5
#define CONFIG_PTHREAD_TASK_STACK_SIZE_DEFAULT 3072
#define CONFIG_PTHREAD_STACK_MIN 768
#define CONFIG_PTHREAD_TASK_CORE_DEFAULT -1
#define CONFIG_PTHREAD_TASK_NAME_DEFAULT "pthread"

/* Logging defaults expected by ESP-IDF and Arduino public headers. */
#define CONFIG_LOG_DEFAULT_LEVEL_INFO 1
#define CONFIG_LOG_DEFAULT_LEVEL 3
#define CONFIG_LOG_MAXIMUM_LEVEL_DEBUG 1
#define CONFIG_LOG_MAXIMUM_LEVEL 4
#define CONFIG_LOG_COLORS 1
#define CONFIG_LOG_TIMESTAMP_SOURCE_RTOS 1
#define CONFIG_LOG_TAG_LEVEL_IMPL_NONE 1
#define CONFIG_LOG_TAG_LEVEL_IMPL 0

/* lwIP settings.  These retain the networking shape of the previous host
 * configuration while supplying the explicit choices required by IDF 6. */
#define CONFIG_LWIP_IPV4 1
#define CONFIG_LWIP_IPV6 1
#define CONFIG_LWIP_ND6 1
#define CONFIG_LWIP_IPV6_AUTOCONFIG 1
#define CONFIG_LWIP_IPV6_NUM_ADDRESSES 3
#define CONFIG_LWIP_IPV6_RDNSS_MAX_DNS_SERVERS 0
#define CONFIG_LWIP_IPV6_MEMP_NUM_ND6_QUEUE 3
#define CONFIG_LWIP_IPV6_ND6_NUM_NEIGHBORS 5
#define CONFIG_LWIP_IPV6_ND6_NUM_PREFIXES 5
#define CONFIG_LWIP_IPV6_ND6_NUM_ROUTERS 3
#define CONFIG_LWIP_IPV6_ND6_NUM_DESTINATIONS 10
#define CONFIG_LWIP_IPV6_DUP_DETECT_ATTEMPTS 1
#define CONFIG_LWIP_IPV6_ND6_NUM_ROUTE_INFO 10
#define CONFIG_LWIP_MAX_SOCKETS 16
#define CONFIG_LWIP_MAX_RAW_PCBS 16
#define CONFIG_LWIP_MAX_ACTIVE_TCP 16
#define CONFIG_LWIP_MAX_LISTENING_TCP 16
#define CONFIG_LWIP_MAX_UDP_PCBS 16
#define CONFIG_LWIP_IP_REASS_MAX_PBUFS 10
#define CONFIG_LWIP_IP_DEFAULT_TTL 64
#define CONFIG_LWIP_IP4_FRAG 1
#define CONFIG_LWIP_IP6_FRAG 1
#define CONFIG_LWIP_DHCP_DISABLE_VENDOR_CLASS_ID 1
#define CONFIG_LWIP_DHCP_OPTIONS_LEN 128
#define CONFIG_LWIP_DHCP_COARSE_TIMER_SECS 1
#define CONFIG_LWIP_DNS_MAX_HOST_IP 1
#define CONFIG_LWIP_DNS_MAX_SERVERS 3
#define CONFIG_LWIP_NETIF_LOOPBACK 1
#define CONFIG_LWIP_LOOPBACK_MAX_PBUFS 8
#define CONFIG_LWIP_TCP_HIGH_SPEED_RETRANSMISSION 1
#define CONFIG_LWIP_TCP_MAXRTX 12
#define CONFIG_LWIP_TCP_SYNMAXRTX 6
#define CONFIG_LWIP_TCP_MSS 1436
#define CONFIG_LWIP_TCP_TMR_INTERVAL 250
#define CONFIG_LWIP_TCP_MSL 60000
#define CONFIG_LWIP_TCP_FIN_WAIT_TIMEOUT 20000
#define CONFIG_LWIP_TCP_SND_BUF_DEFAULT 5744
#define CONFIG_LWIP_TCP_WND_DEFAULT 5744
#define CONFIG_LWIP_TCP_RECVMBOX_SIZE 6
#define CONFIG_LWIP_TCP_ACCEPTMBOX_SIZE 6
#define CONFIG_LWIP_TCP_QUEUE_OOSEQ 1
#define CONFIG_LWIP_TCP_OOSEQ_MAX_PBUFS 4
#define CONFIG_LWIP_TCP_OOSEQ_TIMEOUT 6
#define CONFIG_LWIP_TCP_OVERSIZE_MSS 1
#define CONFIG_LWIP_TCP_RCV_SCALE 0
#define CONFIG_LWIP_TCP_RTO_TIME 3000
#define CONFIG_LWIP_TCPIP_RECVMBOX_SIZE 32
#define CONFIG_LWIP_UDP_RECVMBOX_SIZE 6
#define CONFIG_LWIP_BRIDGEIF_MAX_PORTS 7
#define CONFIG_LWIP_SNTP_MAX_SERVERS 3
#define CONFIG_LWIP_ESP_GRATUITOUS_ARP 1
#define CONFIG_LWIP_GARP_TMR_INTERVAL 60

/* Arduino-as-a-component defaults; its custom main remains responsible for
 * starting the scheduler in roo_testing. */
#define CONFIG_AUTOSTART_ARDUINO 1
#define CONFIG_ARDUINO_LOOP_STACK_SIZE 8192
#define CONFIG_ARDUINO_RUNNING_CORE 0
#define CONFIG_ARDUINO_EVENT_RUNNING_CORE 0
#define CONFIG_ARDUINO_SERIAL_EVENT_TASK_RUNNING_CORE -1
#define CONFIG_ARDUINO_SERIAL_EVENT_TASK_STACK_SIZE 2048
#define CONFIG_ARDUINO_SERIAL_EVENT_TASK_PRIORITY 24
#define CONFIG_ARDUHAL_LOG_DEFAULT_LEVEL 1
#define CONFIG_ARDUHAL_ESP_LOG 1

/* Compatibility names retained by ESP-IDF public APIs. */
#define CONFIG_MAIN_TASK_STACK_SIZE CONFIG_ESP_MAIN_TASK_STACK_SIZE
#define CONFIG_TIMER_TASK_PRIORITY CONFIG_FREERTOS_TIMER_TASK_PRIORITY
#define CONFIG_TIMER_QUEUE_LENGTH CONFIG_FREERTOS_TIMER_QUEUE_LENGTH
#define CONFIG_TIMER_TASK_STACK_DEPTH CONFIG_FREERTOS_TIMER_TASK_STACK_DEPTH
