load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "temperature",
    hdrs = ["temperature.h"],
    visibility = ["//visibility:public"],
    deps = ["//roo_testing/transducers"],
)
