cc_library(
    name = "voltage",
    srcs = ["voltage.cpp"],
    hdrs = ["voltage.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//roo_testing/transducers",
        "@com_github_google_glog//:glog",
    ],
)
