load("//roo_testing/frameworks/esp-idf-v4.4.1:legacy_aliases.bzl", "legacy_idf_aliases")

legacy_idf_aliases([
    "include",
    "rtc_io",
    "cpu",
    "touch_sensor",
    "gpio",
    "adc",
    "spi",
    "ledc",
    "timer",
    "spi_flash",
    "i2c",
    "i2s",
    "interrupt_controller",
    "clk_gate",
    "wdt",
    "uart",
    "soc",
])
