cc_library(
    name = "include",
    hdrs = glob(["include/**/*.h"]),
    includes = [
        "include",
        "include/apps",
    ],
    visibility = ["//visibility:public"],
    deps = [
    ],
)
