alias(name = "esp32", actual = "//roo_testing/frameworks/arduino-esp32/cores/esp32", visibility = ["//visibility:public"])
alias(name = "arduino", actual = "//roo_testing/frameworks/arduino-esp32/cores/esp32:arduino", visibility = ["//visibility:public"])
alias(name = "main", actual = "//roo_testing/frameworks/arduino-esp32/cores/esp32:main", visibility = ["//visibility:public"])
alias(name = "gtest_main", actual = "//roo_testing/frameworks/arduino-esp32/cores/esp32:gtest_main", visibility = ["//visibility:public"])
