load("//roo_testing/frameworks/esp-idf-v4.4.1:legacy_aliases.bzl", "legacy_idf_aliases")

legacy_idf_aliases([
    "include",
    "rtc_io_hal",
    "systimer_hal",
    "spi_hal",
    "ledc_hal",
    "timer_hal",
    "eth_hal",
    "uart_hal",
    "spi_flash_hal",
    "cpu_hal",
    "touch_sensor_hal",
    "gpio_hal",
    "adc_hal",
    "i2c_hal",
    "i2s_hal",
    "interrupt_controller_hal_public",
    "interrupt_controller_hal",
    "wdt_hal",
])
