
cc_library(
    name = "spi",
    hdrs = ["xpt2046spi.h"],
    deps = [
        "//roo_testing/buses/spi",
        "//roo_testing/transducers/ui/viewport",
        "@glog//:glog",
    ],
    visibility = ["//visibility:public"],
)

