
cc_library(
    name = "spi",
    srcs = ["ssd1327spi.cpp"],
    hdrs = ["ssd1327spi.h"],
    deps = [
        "//roo_testing/buses/spi",
        "//roo_testing/transducers/ui/viewport",
    ],
    visibility = ["//visibility:public"],
)

