
cc_library(
    name = "gpio",
    srcs = ["fake_gpio.cpp"],
    hdrs = ["fake_gpio.h"],
    visibility = ["//visibility:public"],
    deps = [
        "@glog//:glog",
        "//roo_testing/transducers/voltage"
    ]
)

