
cc_library(
    name = "esp32",
    srcs = ["fake_esp32.cpp"],
    hdrs = ["fake_esp32.h"],
    deps = [
        "//roo_testing/buses/gpio",
        "//roo_testing/buses/i2c",
        "//roo_testing/buses/spi",
        "@com_github_google_glog//:glog",
    ],
    visibility = ["//visibility:public"],
)

