
cc_library(
    name = "roo_transceivers",
    # srcs = ["fake_transceivers.cpp"],
    hdrs = ["fake_transceivers.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//lib/roo_transceivers",
    ],
)

