
cc_library(
    name = "ft6x36",
    srcs = ["ft6x36.cpp"],
    hdrs = ["ft6x36.h"],
    deps = [
        "//roo_testing/buses/i2c",
        "//roo_testing/transducers/ui/viewport",
        "@com_github_google_glog//:glog",
    ],
    visibility = ["//visibility:public"],
)

