cc_library(
    name = "wifi",
    srcs = ["wifi.cpp"],
    hdrs = ["wifi.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//roo_testing/transducers",
        "@com_github_google_glog//:glog",
    ],
)
