
cc_library(
    name = "spi",
    srcs = ["ili9488spi.cpp"],
    hdrs = ["ili9488spi.h"],
    deps = [
        "//roo_testing/buses/spi",
        "//roo_testing/transducers/ui/viewport",
        "@glog//:glog",
    ],
    visibility = ["//visibility:public"],
)

