load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_test(
    name = "legacy_sd_headers_test",
    srcs = ["legacy_sd_headers_test.cpp"],
    linkstatic = 1,
    deps = [
        "//roo_testing/frameworks/arduino-esp32-2.0.4/libraries/SD",
    ],
)
