
cc_library(
    name = "spi",
    hdrs = ["touch_xpt2046spi.h"],
    deps = [
        "//roo_testing/buses/spi",
        "//roo_testing/transducers/ui:viewport",
        "@com_github_google_glog//:glog",
    ],
    visibility = ["//visibility:public"],
)

