
cc_library(
    name = "fltk",
    srcs = [
        "fltk_viewport.cpp",
    ],
    hdrs = [
        "fltk_viewport.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//roo_testing/transducers/ui/viewport",
        "//fltk-1.3.5:fltk",
    ],
)
