cc_library(
    name = "spi",
    srcs = ["fake_spi.cpp"],
    hdrs = ["fake_spi.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//roo_testing/buses/gpio",
        "@glog",
    ],
)
