cc_library(
    name = "pcf8574",
    srcs = ["pcf8574.cpp"],
    hdrs = ["pcf8574.h"],
    deps = [
        "//roo_testing/buses/i2c",
        "//roo_testing/buses/gpio",
        "@glog//:glog",
    ],
    visibility = ["//visibility:public"],
)

