load("//roo_testing/frameworks/esp-idf-v4.4.1:legacy_aliases.bzl", "legacy_idf_aliases")

legacy_idf_aliases([
    "include",
    "soc_spinlock",
    "soc_cpu",
    "mac_addr",
    "esp_cpu",
    "esp_sleep",
    "esp_mac",
    "esp_chip_info",
    "esp_interface",
    "esp_random",
    "soc_esp32",
    "esp_clk",
    "intr_alloc",
])
