alias(name = "freertos", actual = "//roo_testing/frameworks/esp-idf/components/freertos", visibility = ["//visibility:public"])
alias(name = "include", actual = "//roo_testing/frameworks/esp-idf/components/freertos:include", visibility = ["//visibility:public"])
