
cc_library(
    name = "display_ssd1327spi",
    srcs = ["ssd1327spi.cpp"],
    hdrs = ["ssd1327spi.h"],
    deps = [
        "//roo_testing/buses/spi",
    ],
    visibility = ["//visibility:public"],
)

