load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "timer",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]),
    visibility = ["//visibility:public"],
)

cc_library(
    name = "include",
    hdrs = glob(["*.h"]),
    visibility = ["//visibility:public"],
)
