

cc_library(
    name = "onewire_thermometer",
    srcs = ["fake_onewire_thermometer.cpp"],
    hdrs = ["fake_onewire_thermometer.h"],
    deps = [
        "//roo_testing/buses/onewire",
        "//roo_testing/transducers/temperature",
        "//roo_testing/transducers/time",
    ],
    visibility = ["//visibility:public"],
)

