

cc_library(
    name = "thermometer",
    srcs = ["thermometer.cpp"],
    hdrs = ["thermometer.h"],
    deps = [
        "//roo_testing/buses/onewire",
        "//roo_testing/transducers/temperature",
        "//roo_testing/transducers/time",
    ],
    visibility = ["//visibility:public"],
)

