cc_library(
    name = "include",
    hdrs = glob(["**/*.h"]),
    includes = [
        ".",
    ],
    visibility = ["//visibility:public"],
    deps = [
    ],
)

cc_library(
    name = "assert",
    hdrs = glob(["**/assert.h"]),
    includes = [
        ".",
    ],
    visibility = ["//visibility:public"],
    deps = [
    ],
)

cc_library(
    name = "misc",
    hdrs = glob(["**/misc.h"]),
    includes = [
        ".",
    ],
    visibility = ["//visibility:public"],
    deps = [
    ],
)

cc_library(
    name = "log",
    hdrs = glob(["**/log.h"]),
    includes = [
        ".",
    ],
    visibility = ["//visibility:public"],
    deps = [
    ],
)
