alias(name = "esp-idf-v4.4.1", actual = "//roo_testing/frameworks/esp-idf", visibility = ["//visibility:public"])
alias(name = "esp-idf", actual = "//roo_testing/frameworks/esp-idf", visibility = ["//visibility:public"])
alias(name = "core", actual = "//roo_testing/frameworks/esp-idf:core", visibility = ["//visibility:public"])
alias(name = "sdkconfig", actual = "//roo_testing/frameworks/esp-idf:sdkconfig", visibility = ["//visibility:public"])
