load("//roo_testing/frameworks/esp-idf-v4.4.1:legacy_aliases.bzl", "legacy_idf_aliases")

legacy_idf_aliases([
    "include",
    "rtc_io",
    "gpio",
    "uart",
    "i2c",
    "ledc",
    "timer",
    "adc",
    "i2s",
    "spi",
    "sdspi",
    "sdmmc",
    "periph_ctrl",
])
