

cc_library(
    name = "ds3231",
    srcs = ["fake_i2c_ds3231.cpp"],
    hdrs = ["fake_i2c_ds3231.h"],
    deps = [
        "//roo_testing/buses/i2c",
        "//roo_testing/transducers/time",
        "//roo_testing/transducers/temperature",
    ],
    visibility = ["//visibility:public"],
)

