cc_library(
    name = "onewire",
    srcs = [
        "OneWire.cpp",
        "fake_onewire.cpp",
    ],
    hdrs = [
        "OneWire.h",
        "fake_onewire.h",
    ],
    visibility = ["//visibility:public"],
)
