load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "onewire",
    srcs = [
        "OneWire.cpp",
        "fake_onewire.cpp",
    ],
    hdrs = [
        "OneWire.h",
        "fake_onewire.h",
    ],
    visibility = ["//visibility:public"],
)
