
cc_library(
    name = "combo_makerfabs_tft_capacitive_35",
#    srcs = ["combo_makerfabs_tft_capacitive_35.cpp"],
    hdrs = ["combo_makerfabs_tft_capacitive_35.h"],
    deps = [
        "//roo_testing/buses/i2c",
        "//roo_testing/buses/spi",
        "//roo_testing/devices/display/ili9488:spi",
        "//roo_testing/devices/touch/ft6x36",
        "//roo_testing/transducers/ui/viewport:flex",
        "//roo_testing/transducers/ui/viewport/fltk",
        "//roo_testing/frameworks/arduino-esp32-2.0.4/cores/esp32:main",
        "@glog//:glog",
    ],
    visibility = ["//visibility:public"],
)

